from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('calificacion.views',
	url(r'^cursos-desaprobado/(?P<alumno_codigo>\d+)/json/$','get_curso_desaprobado',name='calificacion-curso-desaprobado'),
	#(r'^anular/$','wvbacademico.views.anular'),
	#(r'^pension/$','wvbacademico.views.pago_pension'),
	#(r'^recuepracion/$','wvbacademico.views.pago_nota'),
	#(r'^pago/$','wvbacademico.views.pago'),
	#(r'^registro-academico/$','wvbacademico.views.registro_academico'),
	#(r'^sustitutorio/$','wvbacademico.views.sustitutorio'),
	#(r'^historial-academico/$','wvbacademico.views.historial_academico'),
	#(r'^boletas/$','wvbacademico.views.boletas'),
	#(r'^form/campus/$','wvbacademico.views.campus'),
	#(r'^form/pension/$','wvbacademico.views.pago_pension'),
	#(r'^form/registro_academico/$','wvbacademico.views.registro_academico'),
	#(r'^form/pago-subsanar/$','wvbacademico.views.pago_nota'),
	#(r'^form/sustitutorio/$','wvbacademico.views.sustitutorio'),
	#(r'^form/pago/$','wvbacademico.views.pago'),
	#(r'^include/menuacademico/$','wvbacademico.views.menuacademico'),
	#(r'^include/menupago/$','wvbacademico.views.menupago'),
	#(r'^json/carrera/(?P<carrera_id>\d+)/$','wvbacademico.views.carrera_json'),
	#(r'^json/docente/(?P<docente_id>\d+)/$','wvbacademico.views.docente_json'),
	#(r'^json/ciclo/(?P<carrera_id>\d+)/$','wvbacademico.views.ciclo_json'),
	#(r'^json/curso/(?P<curso_id>\d+)/$','wvbacademico.views.curso_json'),
	#(r'^json/boleta-campus/(?P<codigo_alumno>\d+)/$','wvbacademico.views.alumno_boleta_json'),
	#(r'^json/boleta-general/(?P<codigo_alumno>\d+)/$','wvbacademico.views.general_boleta_json'),
	#(r'^json/nota_boleta_json/(?P<codigo_alumno>\d+)/$','wvbacademico.views.nota_boleta_json'),
	#(r'^json/boletas/(?P<fecha_inicio>\w+)-(?P<fecha_fin>\w+)-(?P<hoy>\d+)-(?P<rows>\d+)/$','wvbacademico.views.boletas_json'),
	#(r'^ajax/ciclo/(?P<carrera_id>\d+)/$','wvbacademico.views.ciclo_ajax'),
	#(r'^ajax/historial-academico/(?P<alumno_codigo>\w+)/$','wvbacademico.views.historial_academico_ajax'),
	#(r'^ajax/notas-desaprovadas/(?P<codigo_alumno>\d+)/$','wvbacademico.views.sustitutorio_ajax'),
	#(r'^ajax/registro-academico-ajax/(?P<ciclo_id>\d+)-(?P<fecha_inicio>\w+)-(?P<seccion>\w+)-(?P<semestre>\d+)/$','wvbacademico.views.registro_academico_ajax'),
	#(r'^ajax/curso/(?P<ciclo_id>\d+)/$','wvbacademico.views.curso_ajax'),
	#(r'^ajax/asignaturas/(?P<ciclo_id>\d+)/$','wvbacademico.views.asignaturas_ajax'),
	#(r'^ajax/alumno-campus/(?P<ciclo_id>\d+)-(?P<fecha_inicio>\w+)-(?P<seccion>\w+)-(?P<semestre>\d+)/$','wvbacademico.views.alumnos_matriculados_ajax'),
)
